export enum BASE_ROUTES {
    GUEST_PANEL = 'panel-goscia',
    HOME = 'strona-glowna',
    INVITE_CONFIRMATION = 'potwierdz-zaproszenie',
    ENTER_CODE = 'wprowadz-kod',
    ADMIN = 'admin',
    LOGIN = 'logowanie',
    MANAGE_INVITATIONS = 'zarzadzaj-zaproszeniami',
    SINGBOOK = 'spiewnik',
}

export enum ROUTE {
    HOME = `/${BASE_ROUTES.GUEST_PANEL}/${BASE_ROUTES.HOME}`,
    INVITE_CONFIRMATION = `/${BASE_ROUTES.GUEST_PANEL}/${BASE_ROUTES.INVITE_CONFIRMATION}`,
    ENTER_CODE = `/${BASE_ROUTES.GUEST_PANEL}/${BASE_ROUTES.ENTER_CODE}`,
    ADMIN_LOGIN = `/${BASE_ROUTES.ADMIN}/${BASE_ROUTES.LOGIN}`,
    ADMIN_MANAGE_INVITATIONS = `/${BASE_ROUTES.ADMIN}/${BASE_ROUTES.MANAGE_INVITATIONS}`,
    SINGBOOK = `/${BASE_ROUTES.GUEST_PANEL}/${BASE_ROUTES.SINGBOOK}`,
}